
  services:
    postgres:
      image: postgres:14
      container_name: noora_postgres
      restart: always
      environment:
        POSTGRES_DB: noora_db
        POSTGRES_USER: noora_user
        POSTGRES_PASSWORD: noora_pass
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data

  pyspark:
    build: .
    container_name: noora_pyspark
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: sleep infinity
  
  volumes:
    pg_data:

